# Generated by Django 2.0.13 on 2019-06-17 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20190616_1846'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='picture',
        ),
        migrations.AddField(
            model_name='news',
            name='main_picture',
            field=models.ImageField(blank=True, max_length=200, upload_to=''),
        ),
    ]
