# Generated by Django 2.0.13 on 2019-06-24 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TYPE', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('cousine', models.CharField(max_length=200)),
                ('TYPE', models.CharField(max_length=200)),
                ('products', models.TextField(help_text='All words in lowercase and no spaces, use comma as a divider', null=True)),
                ('comments', models.CharField(max_length=200)),
                ('avg_point', models.PositiveSmallIntegerField(default=3)),
            ],
        ),
        migrations.CreateModel(
            name='MealHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('point', models.NullBooleanField()),
                ('location', models.CharField(max_length=200)),
                ('weight', models.PositiveSmallIntegerField()),
                ('acne', models.PositiveSmallIntegerField()),
                ('accepted', models.BooleanField()),
                ('dish', models.ForeignKey(db_index=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='map.Dish')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('region', models.CharField(max_length=200)),
                ('TYPE', models.CharField(max_length=200)),
                ('comments', models.CharField(max_length=200)),
                ('avg_point', models.PositiveSmallIntegerField(default=3)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ext_id', models.CharField(max_length=200, unique=True)),
                ('name', models.CharField(max_length=200, null=True)),
                ('surname', models.CharField(max_length=200, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('telegram', models.CharField(max_length=200, null=True)),
                ('registration', models.DateTimeField(auto_now_add=True)),
                ('birthday', models.DateField(null=True)),
                ('length', models.PositiveSmallIntegerField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='mealhistory',
            name='user',
            field=models.ForeignKey(db_index=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='map.User'),
        ),
        migrations.AddField(
            model_name='device',
            name='allowed_users',
            field=models.ManyToManyField(to='map.User'),
        ),
    ]
