# Generated by Django 2.0.13 on 2019-06-24 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mealhistory',
            name='acne',
            field=models.PositiveSmallIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='mealhistory',
            name='dish',
            field=models.ForeignKey(blank=True, db_index=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='map.Dish'),
        ),
        migrations.AlterField(
            model_name='mealhistory',
            name='location',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='mealhistory',
            name='user',
            field=models.ForeignKey(blank=True, db_index=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='map.User'),
        ),
        migrations.AlterField(
            model_name='mealhistory',
            name='weight',
            field=models.PositiveSmallIntegerField(blank=True),
        ),
    ]
