# Generated by Django 2.0.13 on 2019-06-24 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0002_auto_20190624_2201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='comments',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='mealhistory',
            name='acne',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mealhistory',
            name='weight',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='comments',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
