# Generated by Django 2.0.13 on 2019-06-25 12:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
        ('map', '0004_auto_20190625_1217'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserApp',
            fields=[
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('name', models.CharField(max_length=200, null=True)),
                ('surname', models.CharField(max_length=200, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('telegram', models.CharField(max_length=200, null=True)),
                ('registration', models.DateTimeField(auto_now_add=True)),
                ('birthday', models.DateField(null=True)),
                ('length', models.PositiveSmallIntegerField(null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AlterField(
            model_name='device',
            name='allowed_users',
            field=models.ManyToManyField(to='map.UserApp'),
        ),
    ]
