# Generated by Django 2.0.13 on 2019-06-25 13:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('map', '0009_auto_20190625_1558'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='products',
            field=models.TextField(blank=True, help_text='All words in lowercase and no spaces, use comma as a divider', null=True),
        ),
    ]
