# Generated by Django 2.0.13 on 2019-06-25 13:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0010_auto_20190625_1635'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appuser',
            name='user',
        ),
        migrations.AlterField(
            model_name='appuser',
            name='id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
