# Generated by Django 2.0.13 on 2019-06-25 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0013_auto_20190625_1644'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='allowed_users',
        ),
    ]
