# Generated by Django 2.0.13 on 2019-06-25 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0014_remove_device_allowed_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='allowed_users',
            field=models.ManyToManyField(to='map.AppUser'),
        ),
    ]
