# Generated by Django 2.0.13 on 2019-06-25 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0015_device_allowed_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
