# Generated by Django 2.0.13 on 2019-07-08 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0016_auto_20190625_1739'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegionVector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preference', models.PositiveSmallIntegerField(blank=True)),
                ('region', models.CharField(blank=True, default='russia', max_length=200, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='product',
            old_name='TYPE',
            new_name='group',
        ),
        migrations.RemoveField(
            model_name='product',
            name='region',
        ),
        migrations.AddField(
            model_name='appuser',
            name='region',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='appuser',
            name='weigth',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dish',
            name='carbs',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='dish',
            name='fats',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='dish',
            name='frequency',
            field=models.CharField(default=30, max_length=200),
        ),
        migrations.AddField(
            model_name='dish',
            name='kcal',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='dish',
            name='proteins',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='dish',
            name='region',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='dish',
            name='specials_cousine',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='dish',
            name='tags',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='carbs',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='fats',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='kcal',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='proteins',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='season',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.RemoveField(
            model_name='device',
            name='allowed_users',
        ),
        migrations.AddField(
            model_name='device',
            name='allowed_users',
            field=models.ForeignKey(blank=True, db_index=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='map.AppUser'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='avg_point',
            field=models.PositiveSmallIntegerField(default=30),
        ),
        migrations.AlterField(
            model_name='product',
            name='avg_point',
            field=models.PositiveSmallIntegerField(default=30),
        ),
        migrations.AddField(
            model_name='regionvector',
            name='name',
            field=models.ForeignKey(blank=True, db_index=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='map.Dish'),
        ),
    ]
