# Generated by Django 2.0.13 on 2019-07-09 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0017_auto_20190708_1144'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='regionvector',
            name='name',
        ),
        migrations.RemoveField(
            model_name='regionvector',
            name='preference',
        ),
        migrations.AddField(
            model_name='regionvector',
            name='date_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='regionvector',
            name='dishes',
            field=models.TextField(default=12),
            preserve_default=False,
        ),
    ]
