# Generated by Django 2.0.13 on 2019-07-26 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0019_auto_20190726_1837'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='public_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='region',
            name='borders',
            field=models.TextField(blank=True),
        ),
    ]
