# Generated by Django 2.0.13 on 2019-07-28 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0020_auto_20190726_1923'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dish',
            old_name='specials_cousine',
            new_name='specials_rules',
        ),
    ]
