# Generated by Django 2.0.13 on 2019-07-28 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0022_remove_dish_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='tags',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
