# Generated by Django 2.0.13 on 2019-07-29 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0023_dish_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='parsed',
            field=models.BooleanField(default='False'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mealhistory',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
    ]
