# Generated by Django 2.0.13 on 2019-07-29 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0024_auto_20190729_1425'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='group',
            new_name='TYPE',
        ),
    ]
