# Generated by Django 2.0.13 on 2019-07-29 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0025_auto_20190729_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='TYPE',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
