# Generated by Django 2.0.13 on 2019-08-09 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0027_auto_20190729_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mealhistory',
            name='location',
            field=models.CharField(default='russia', max_length=200),
        ),
        migrations.AlterField(
            model_name='product',
            name='avg_point',
            field=models.PositiveSmallIntegerField(default=30),
        ),
    ]
