# Generated by Django 2.0.13 on 2019-08-20 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0029_auto_20190820_1218'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mealhistory',
            name='dish',
        ),
    ]
