# Generated by Django 2.0.13 on 2019-08-20 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0030_remove_mealhistory_dish'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealhistory',
            name='dish',
            field=models.ForeignKey(blank=True, db_index=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='map.Dish'),
        ),
    ]
