# Generated by Django 2.0.13 on 2019-08-21 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0031_mealhistory_dish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='TYPE',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='dish',
            name='cousine',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
