# Generated by Django 2.0.13 on 2019-08-26 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0034_auto_20190826_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preference',
            name='last_meal_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
