# Generated by Django 2.0.13 on 2019-08-28 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0038_auto_20190826_2114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='region',
            field=models.ForeignKey(blank=True, db_index=False, default='russia', null=True, on_delete=django.db.models.deletion.SET_NULL, to='map.Region'),
        ),
        migrations.AlterField(
            model_name='mealhistory',
            name='user',
            field=models.ForeignKey(blank=True, db_index=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='map.AppUser'),
        ),
    ]
