# Generated by Django 2.0.13 on 2019-08-28 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0040_auto_20190828_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mealhistory',
            name='user',
            field=models.ForeignKey(blank=True, db_index=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='map.AppUser'),
        ),
    ]
