# Generated by Django 2.0.13 on 2019-09-10 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0041_auto_20190828_1447'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='alt_names',
            field=models.TextField(blank=True, help_text='All names in lowercase, use comma as a divider', null=True),
        ),
        migrations.AddField(
            model_name='dish',
            name='cooking_method',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='dish',
            name='eng_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='preference',
            name='last_meal_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
