# Generated by Django 2.0.13 on 2019-09-13 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0042_auto_20190910_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='length',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='weigth',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
