# Generated by Django 2.0.13 on 2019-09-30 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0043_auto_20190913_1441'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dish',
            name='alt_names',
        ),
        migrations.RemoveField(
            model_name='dish',
            name='cooking_method',
        ),
        migrations.RemoveField(
            model_name='dish',
            name='eng_name',
        ),
    ]
