# Generated by Django 2.0.13 on 2019-10-02 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0045_auto_20190930_1545'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dish',
            name='weights',
            field=models.TextField(blank=True, help_text='Just numbers of weights of products in the same order as porducts, use comma as a divider', null=True),
        ),
    ]
