# Generated by Django 2.0.13 on 2019-10-03 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0046_auto_20191002_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preference',
            name='weight_effect',
            field=models.SmallIntegerField(default=0),
        ),
    ]
