# Generated by Django 2.0.13 on 2019-06-13 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('desc', models.CharField(max_length=400)),
                ('keywords', models.CharField(max_length=200)),
                ('seo_text', models.TextField()),
            ],
        ),
    ]
