# Generated by Django 2.0.13 on 2019-06-17 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_page_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('active', models.BooleanField()),
                ('title', models.CharField(blank=True, max_length=200)),
                ('desc', models.TextField()),
                ('button_text', models.CharField(default='More', max_length=200)),
                ('link', models.CharField(max_length=200)),
                ('image', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
