# Generated by Django 2.0.13 on 2019-06-17 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_banner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banner',
            name='name',
        ),
        migrations.AlterField(
            model_name='banner',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
