# Generated by Django 2.0.13 on 2019-06-13 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='allowed_users',
            field=models.ManyToManyField(to='app.User'),
        ),
    ]
