# Generated by Django 2.0.13 on 2019-06-13 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20190613_2057'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='lenght',
            new_name='length',
        ),
        migrations.AlterField(
            model_name='user',
            name='ext_id',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
