# Generated by Django 2.0.13 on 2019-06-24 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='main_picture',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
