# Generated by Django 2.0.13 on 2019-09-30 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dishlist_manager', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DishManager',
            new_name='DishList',
        ),
    ]
